// Tests for the User Controller

### Users endpoint
@domain = http://localhost:3000/
@endpoint = users/
@url = {{domain}}{{endpoint}}


### Create User, default values for Role and email
### Return Status 201
# @name createUser
POST  {{url}} HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "name": "judas",
    "dni": "25666666",
    "password": "j"
}


### Read last created User
### Return Status 200
@userId = {{createUser.response.body.$.user.id}}
GET {{url}}{{userId}} HTTP/1.1
Accept: application/json


### Read an existing User
### Return Status 200
@id = 23000115
GET {{url}}{{id}} HTTP/1.1
Accept: application/json


### Read a non-existent User
### Return Status 200
@userIdNonExistent = -10
GET {{url}}{{userIdNonExistent}} HTTP/1.1
Accept: application/json


### Read a User, wrong parameters
### Return Status 200
@userIdWrongValue = juan
GET {{url}}{{userIdWrongValue}} HTTP/1.1
Accept: application/json

